name: x86-64 Download Build File
on:
  workflow_dispatch:
    inputs:
      file_urls:
        description: '请填写地址 多个用英文逗号分开'
        required: true
        default: 'alpine:latest'  # 设置默认的

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean up Docker to free space
      run: |
          docker system prune -a -f
          docker volume prune -f

    - name: Pull file_urls and Package
      run: |
        images="${{ github.event.inputs.file_urls }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do          
          wget -o "${image//\//_}-amd64.tar" "${image}"
        done

    - name: Compress the TAR files
      run: tar -czf x86-64-images.tar.gz *-amd64.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar
        path: x86-64-images.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm *-amd64.tar
